remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: ['Хакатон Лента х Практикум сентябрь’23. Команда 20']
description: ['Cоздание предсказательной модели и его интерфейса по прогнозированию спроса на товары заказчика собственного производства ООО “Лента”.']
